---
- hosts: workshop
  become: true
  become_method: sudo

  tasks:
  - name: "Ensure authorized key is installed for user pi"
    authorized_key:
      user: pi
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: "Ensure all dependancies are installed"
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - ieee-data
      - python3-pip
      - python3-netaddr
      - python3-kerberos
      - python3-selinux
      - python3-xmltodict
      - python3-httplib2
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-cryptography
      - python3-setuptools
      - sshpass
      - git

  - name: "Ensure pip modules are installed"
    pip:
      name: pywinrm


  - name: "Ensure ansible is installed"
    pip:
      name: ansible
      version: "2.9.27"

  - name: "Ensure Ansible workshop files are copied to the pi"
    copy:
      src: "{{ item }}"
      dest: "/home/pi/{{ item }}"
      owner: "pi"
      group: "pi"
    loop:
    - ansible.cfg
    - inventory
    - workshop.yml

  - name: "Ensure SSH key is installed on the pi"
    copy:
      src: "~/.ssh/{{ item }}"
      dest: "/home/pi/.ssh/{{ item }}"
      owner: "pi"
      group: "pi"
      mode: "0600"
    loop:
    - id_rsa
    - id_rsa.pub

  - name: "Ensure foo is copied and decrypted"
    template:
      src: foo
      dest: /home/pi/foo
